# Generated by Django 5.0.6 on 2024-05-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
