# Generated by Django 5.0.6 on 2024-05-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_admin_admin_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_password',
        ),
    ]
