# Generated by Django 5.0.6 on 2024-05-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=30)),
                ('patient_last_name', models.CharField(max_length=20)),
                ('p_birth_date', models.DateField()),
                ('p_gender', models.CharField(max_length=1)),
                ('phone_number', models.CharField(max_length=11)),
                ('p_address', models.TextField()),
            ],
        ),
    ]
