# Generated by Django 5.0.6 on 2024-05-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=20)),
                ('doctor_last_name', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=30)),
                ('hospital_works_in', models.CharField(max_length=30)),
            ],
        ),
    ]
